version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/nome_do_banco

  db:
    image: postgres:13
    ports:
      - "5411:5432"  # Mapeie a porta 5411 externa para 5432 interna
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=nome_do_banco
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: